### ISSUE TITLE
Написать workflow главной задачи. Минимум - 15 use-cases (Сценариев)

### ISSUE THREAD

**Issue by vlasival** [NSU-Software-Disign-Project/chatbot-editor-main#1]
Юз-кейс - это набор действий (глагол). Существуют отношения между юз-кейсами - расширения, один кейс включает другой.

**Comment by izabellllia** [comment]
https://docs.google.com/document/d/1c8mzYaF5sWzi8ybmPQl0cqgRqkzQEae2RoJn5e5yilc/edit?usp=sharing
